[package]
name = "slope_staker"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.0"
epaint = "0.31.0"
chrono = "0.4.40"
fixed = "1"
strum = "0.26"
strum_macros = "0.26"
egui-plotter = "0.6.0"
